name: Run PHP Script

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'

      - name: List files in biblioteca directory
        run: ls -la biblioteca

      - name: List files in Controller directory
        run: ls -la biblioteca/Controller

      - name: Display content of Load.php
        run: cat biblioteca/Libraries/Core/Load.php

    #  - name: Run PHP Script
    #    run: php biblioteca/index.php

    # Opcional: Ejecutar análisis estático de código con PHPStan
    # - name: Configurar PHPStan
    #   run: composer require --dev phpstan/phpstan
    # - name: Ejecutar PHPStan
    #   run: vendor/bin/phpstan analyse --level max

    # Opcional: Ejecutar pruebas unitarias
    # - name: Ejecutar pruebas unitarias
    #   run: phpunit --configuration phpunit.xml

