name: CI/CD para Proyecto PHP Clásico

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout código
      uses: actions/checkout@v4

    - name: Configurar PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.0'  # Puedes ajustar la versión de PHP 

    - name: Validar sintaxis de PHP
      run: |
        Get-ChildItem -Recurse -Filter *.php | ForEach-Object { php -l $_.FullName }

    - name: List files in biblioteca directory
      run: dir biblioteca

    - name: List files in Controller directory
      run: dir biblioteca\Controller

    - name: Display content of Load.php
      run: Get-Content biblioteca\Libraries\Core\Load.php

    # - name: Run PHP Script
    #   run: php biblioteca\index.php

    # Opcional: Ejecutar análisis estático de código con PHPStan
    # - name: Configurar PHPStan
    #   run: composer require --dev phpstan/phpstan
    # - name: Ejecutar PHPStan
    #   run: vendor\bin\phpstan analyse --level max

    # Opcional: Ejecutar pruebas unitarias
    # - name: Ejecutar pruebas unitarias
    #   run: phpunit --configuration phpunit.xml
