name: CI/CD para Proyecto PHP Clásico

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout código
      uses: actions/checkout@v4

    - name: Configurar PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.0'  # Puedes ajustar la versión de PHP según lo que utilices

    - name: Validar sintaxis de PHP
      run: |
        find . -name "*.php" -print0 | xargs -0 -n 1 php -l

    # Opcional: Ejecutar análisis estático de código con PHPStan
    # - name: Configurar PHPStan
    #   run: composer require --dev phpstan/phpstan
    # - name: Ejecutar PHPStan
    #   run: vendor/bin/phpstan analyse --level max

    # Opcional: Ejecutar pruebas unitarias
    # - name: Ejecutar pruebas unitarias
    #   run: phpunit --configuration phpunit.xml

