name: CI for MVC Project

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Check out repository code
      uses: actions/checkout@v4

    - name: Validate PHP syntax
      run: find . -name "*.php" -print0 | xargs -0 -n1 php -l

    - name: Validate composer.json and composer.lock
      run: composer validate --strict

    - name: Install dependencies
      run: composer install --prefer-dist --no-progress

    - name: Run PHPUnit tests
      run: vendor/bin/phpunit --colors=always

    - name: Lint CSS files
      run: |
        find . -name "*.css" -print0 | xargs -0 stylelint

    - name: Lint HTML files
      run: |
        find . -name "*.html" -print0 | xargs -0 htmlhint

    - name: Lint JavaScript files
      run: |
        find . -name "*.js" -print0 | xargs -0 eslint


